# 워크플로우의 이름
name: CI

# 워크플로우가 시작될 조건
# main branch에서 push작업이 일어났을 때
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경
    # 실행 스텝 지정
    steps:
      # uses: 지정한 리포지터리를 확인하고 코드에 대한 작업 실행
      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/application-db.properties
      - run: echo "${{ secrets.DB }}" > ./src/main/resources/application-db.properties
      - run: cat ./src/main/resources/application-db.properties

      - run: touch ./src/main/resources/application-jwt.properties
      - run: echo "${{ secrets.JWT }}" > ./src/main/resources/application-jwt.properties
      - run: cat ./src/main/resources/application-jwt.properties

      - run: touch ./src/main/resources/application-oauth.properties
      - run: echo "${{ secrets.OAUTH2 }}" > ./src/main/resources/application-oauth.properties
      - run: cat ./src/main/resources/application-oauth.properties

      - uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '17'
      # name: 스텝의 이름
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build